name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        # Здесь мы добавили команду 'cd', чтобы зайти в нужную папку
        run: |
          cd BetterSprint-1.21-main/BetterSprint-1.21-main
          chmod +x gradlew

      - name: Build with Gradle
        # И здесь тоже говорим работать внутри папки
        run: |
          cd BetterSprint-1.21-main/BetterSprint-1.21-main
          ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: BetterSprint-Mod
          # Указываем путь к файлу внутри вложенных папок
          path: BetterSprint-1.21-main/BetterSprint-1.21-main/build/libs/*.jar
