- name: Make gradlew executable
        run: |
          cd BetterSprint-1.21-main/BetterSprint-1.21-main
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd BetterSprint-1.21-main/BetterSprint-1.21-main
          ./gradlew build
